# Generated by Django 4.2.7 on 2023-12-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_remove_faculty_sub_faculty_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Departments',
            field=models.ManyToManyField(to='one.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.department'),
        ),
    ]
