# Generated by Django 4.2.7 on 2023-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_department_remove_faculty_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='sub',
        ),
        migrations.AddField(
            model_name='faculty',
            name='sub',
            field=models.ManyToManyField(blank=True, to='one.subject'),
        ),
    ]
